// Code generated by "stringer -type=Status"; DO NOT EDIT.

package request

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusUnknown-0]
	_ = x[SuccessConnect-1]
	_ = x[SuccessReconnect-2]
	_ = x[SuccessDisconnect-3]
	_ = x[SuccessTargetOpen-4]
	_ = x[SuccessTargetUpdate-5]
	_ = x[SuccessTargetClose-6]
	_ = x[SuccessReadDatabaseSchema-7]
	_ = x[SuccessReadTableSchema-8]
	_ = x[SuccessReadColumnSchema-9]
	_ = x[SuccessReadDatabaseProperties-10]
	_ = x[SuccessReadTableProperties-11]
	_ = x[SuccessReadColumnProperties-12]
	_ = x[SuccessReadDatabaseList-13]
	_ = x[SuccessReadDBTableList-14]
	_ = x[SuccessReadDBColumnList-15]
	_ = x[SuccessReadCount-16]
	_ = x[SuccessCreate-17]
	_ = x[SuccessRead-18]
	_ = x[SuccessUpdate-19]
	_ = x[SuccessDelete-20]
	_ = x[SuccessExecute-21]
	_ = x[SuccessBatchExecute-22]
	_ = x[ErrorConnect - -1]
	_ = x[ErrorReconnect - -2]
	_ = x[ErrorDisconnect - -3]
	_ = x[ErrorTargetOpen - -4]
	_ = x[ErrorTargetClose - -5]
	_ = x[ErrorTargetUpdate - -6]
	_ = x[ErrorReadDatabaseSchema - -7]
	_ = x[ErrorReadTableSchema - -8]
	_ = x[ErrorReadColumnSchema - -9]
	_ = x[ErrorReadDatabaseProperties - -10]
	_ = x[ErrorReadTableProperties - -11]
	_ = x[ErrorReadColumnProperties - -12]
	_ = x[ErrorReadDatabaseList - -13]
	_ = x[ErrorReadDBTableList - -14]
	_ = x[ErrorReadDBColumnList - -15]
	_ = x[ErrorReadCount - -16]
	_ = x[ErrorCreate - -17]
	_ = x[ErrorRead - -18]
	_ = x[ErrorUpdate - -19]
	_ = x[ErrorDelete - -20]
	_ = x[ErrorExecute - -21]
	_ = x[ErrorBatchExecute - -22]
}

const _Status_name = "ErrorBatchExecuteErrorExecuteErrorDeleteErrorUpdateErrorReadErrorCreateErrorReadCountErrorReadDBColumnListErrorReadDBTableListErrorReadDatabaseListErrorReadColumnPropertiesErrorReadTablePropertiesErrorReadDatabasePropertiesErrorReadColumnSchemaErrorReadTableSchemaErrorReadDatabaseSchemaErrorTargetUpdateErrorTargetCloseErrorTargetOpenErrorDisconnectErrorReconnectErrorConnectStatusUnknownSuccessConnectSuccessReconnectSuccessDisconnectSuccessTargetOpenSuccessTargetUpdateSuccessTargetCloseSuccessReadDatabaseSchemaSuccessReadTableSchemaSuccessReadColumnSchemaSuccessReadDatabasePropertiesSuccessReadTablePropertiesSuccessReadColumnPropertiesSuccessReadDatabaseListSuccessReadDBTableListSuccessReadDBColumnListSuccessReadCountSuccessCreateSuccessReadSuccessUpdateSuccessDeleteSuccessExecuteSuccessBatchExecute"

var _Status_index = [...]uint16{0, 17, 29, 40, 51, 60, 71, 85, 106, 126, 147, 172, 196, 223, 244, 264, 287, 304, 320, 335, 350, 364, 376, 389, 403, 419, 436, 453, 472, 490, 515, 537, 560, 589, 615, 642, 665, 687, 710, 726, 739, 750, 763, 776, 790, 809}

func (i Status) String() string {
	i -= -22
	if i < 0 || i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i+-22), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
