// Code generated by "stringer -type=Keyword -linecomment=true"; DO NOT EDIT.

package sql

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Select-0]
	_ = x[Insert-1]
	_ = x[Update-2]
	_ = x[Delete-3]
	_ = x[From-4]
	_ = x[Where-5]
	_ = x[Set-6]
	_ = x[Values-7]
	_ = x[OrderBy-8]
	_ = x[Asc-9]
	_ = x[Desc-10]
	_ = x[Limit-11]
	_ = x[Offset-12]
	_ = x[GroupBy-13]
	_ = x[Having-14]
	_ = x[Join-15]
	_ = x[LeftJoin-16]
	_ = x[RightJoin-17]
	_ = x[FullJoin-18]
	_ = x[CrossJoin-19]
	_ = x[On-20]
	_ = x[As-21]
	_ = x[InnerJoin-22]
	_ = x[OuterJoin-23]
	_ = x[Union-24]
	_ = x[Intersect-25]
	_ = x[Except-26]
	_ = x[UnionAll-27]
	_ = x[IntersectAll-28]
	_ = x[ExceptAll-29]
	_ = x[Not-30]
	_ = x[In-31]
	_ = x[Between-32]
	_ = x[And-33]
	_ = x[Or-34]
	_ = x[IsNull-35]
	_ = x[IsNotNull-36]
	_ = x[IsTrue-37]
	_ = x[IsFalse-38]
	_ = x[IsUnknown-39]
	_ = x[IsDistinctFrom-40]
	_ = x[IsNotDistinctFrom-41]
	_ = x[Like-42]
	_ = x[NotLike-43]
	_ = x[Ilike-44]
	_ = x[NotIlike-45]
	_ = x[Any-46]
	_ = x[All-47]
	_ = x[Exists-48]
	_ = x[Some-49]
	_ = x[Unique-50]
	_ = x[PrimaryKey-51]
	_ = x[ForeignKey-52]
	_ = x[Check-53]
	_ = x[Default-54]
	_ = x[Null-55]
	_ = x[True-56]
	_ = x[False-57]
	_ = x[Unknown-58]
	_ = x[Call-59]
	_ = x[Exec-60]
	_ = x[Execute-61]
	_ = x[Pragma-62]
}

const _Keyword_name = "SELECTINSERTUPDATEDELETEFROMWHERESETVALUESORDER BYASCDESCLIMITOFFSETGROUP BYHAVINGJOINLEFT JOINRIGHT JOINFULL JOINCROSS JOINONASINNER JOINOUTER JOINUNIONINTERSECTEXCEPTUNION ALLINTERSECT ALLEXCEPT ALLNOTINBETWEENANDORIS NULLIS NOT NULLIS TRUEIS FALSEIS UNKNOWNIS DISTINCT FROMIS NOT DISTINCT FROMLIKENOT LIKEILIKENOT ILIKEANYALLEXISTSSOMEUNIQUEPRIMARY KEYFOREIGN KEYCHECKDEFAULTNULLTRUEFALSEUNKNOWNCALLEXECEXECUTEPRAGMA"

var _Keyword_index = [...]uint16{0, 6, 12, 18, 24, 28, 33, 36, 42, 50, 53, 57, 62, 68, 76, 82, 86, 95, 105, 114, 124, 126, 128, 138, 148, 153, 162, 168, 177, 190, 200, 203, 205, 212, 215, 217, 224, 235, 242, 250, 260, 276, 296, 300, 308, 313, 322, 325, 328, 334, 338, 344, 355, 366, 371, 378, 382, 386, 391, 398, 402, 406, 413, 419}

func (i Keyword) String() string {
	if i < 0 || i >= Keyword(len(_Keyword_index)-1) {
		return "KeyWord(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Keyword_name[_Keyword_index[i]:_Keyword_index[i+1]]
}
