// Code generated by "stringer -type=EventType"; DO NOT EDIT.

package dribble

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Connected-0]
	_ = x[ConnectError-1]
	_ = x[Reconnected-2]
	_ = x[ReconnectError-3]
	_ = x[Disconnected-4]
	_ = x[DisconnectError-5]
	_ = x[DriverLoadError-6]
	_ = x[TargetOpened-7]
	_ = x[TargetOpenError-8]
	_ = x[TargetClosed-9]
	_ = x[TargetCloseError-10]
	_ = x[TargetUpdated-11]
	_ = x[TargetUpdateError-12]
	_ = x[DBOpened-13]
	_ = x[DBOpenError-14]
	_ = x[DatabaseListFetched-15]
	_ = x[DatabaseListFetchError-16]
	_ = x[DBTableListFetched-17]
	_ = x[DBTableListFetchError-18]
	_ = x[TableSelected-19]
	_ = x[TableSelectError-20]
	_ = x[TableFetched-21]
	_ = x[TableFetchError-22]
	_ = x[TableCountFetched-23]
	_ = x[QueryExecuted-24]
	_ = x[QueryExecuteError-25]
}

const _EventType_name = "ConnectedConnectErrorReconnectedReconnectErrorDisconnectedDisconnectErrorDriverLoadErrorTargetOpenedTargetOpenErrorTargetClosedTargetCloseErrorTargetUpdatedTargetUpdateErrorDBOpenedDBOpenErrorDatabaseListFetchedDatabaseListFetchErrorDBTableListFetchedDBTableListFetchErrorTableSelectedTableSelectErrorTableFetchedTableFetchErrorTableCountFetchedQueryExecutedQueryExecuteError"

var _EventType_index = [...]uint16{0, 9, 21, 32, 46, 58, 73, 88, 100, 115, 127, 143, 156, 173, 181, 192, 211, 233, 251, 272, 285, 301, 313, 328, 345, 358, 375}

func (i EventType) String() string {
	if i >= EventType(len(_EventType_index)-1) {
		return "EventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
