// Code generated by "stringer -type=Position"; DO NOT EDIT.

package layout

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[None-0]
	_ = x[Top-1]
	_ = x[Right-2]
	_ = x[Bottom-3]
	_ = x[Left-4]
	_ = x[Center-5]
}

const _Position_name = "NoneTopRightBottomLeftCenter"

var _Position_index = [...]uint8{0, 4, 7, 12, 18, 22, 28}

func (i Position) String() string {
	if i < 0 || i >= Position(len(_Position_index)-1) {
		return "Position(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Position_name[_Position_index[i]:_Position_index[i+1]]
}
