// Code generated by "stringer -type=DBType,SQLDialectType,NoSQLModelType,GraphType,TimeSeriesType -trimprefix=Type"; DO NOT EDIT.

package database

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeSQL-0]
	_ = x[TypeNoSQL-1]
	_ = x[TypeGraph-2]
	_ = x[TypeTimeSeries-3]
	_ = x[TypeUndefined - -1]
}

const _DBType_name = "UndefinedSQLNoSQLGraphTimeSeries"

var _DBType_index = [...]uint8{0, 9, 12, 17, 22, 32}

func (i DBType) String() string {
	i -= -1
	if i < 0 || i >= DBType(len(_DBType_index)-1) {
		return "DBType(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _DBType_name[_DBType_index[i]:_DBType_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PostgreSQL-0]
	_ = x[MySQL-1]
	_ = x[SQLite3-2]
	_ = x[NumSupportedSQLDialects-3]
}

const _SQLDialectType_name = "PostgreSQLMySQLSQLite3NumSupportedSQLDialects"

var _SQLDialectType_index = [...]uint8{0, 10, 15, 22, 45}

func (i SQLDialectType) String() string {
	if i < 0 || i >= SQLDialectType(len(_SQLDialectType_index)-1) {
		return "SQLDialectType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SQLDialectType_name[_SQLDialectType_index[i]:_SQLDialectType_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MongoDB-0]
	_ = x[Firestore-1]
	_ = x[Redis-2]
	_ = x[NumSupportedNoSQLModels-3]
}

const _NoSQLModelType_name = "MongoDBFirestoreRedisNumSupportedNoSQLModels"

var _NoSQLModelType_index = [...]uint8{0, 7, 16, 21, 44}

func (i NoSQLModelType) String() string {
	if i < 0 || i >= NoSQLModelType(len(_NoSQLModelType_index)-1) {
		return "NoSQLModelType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NoSQLModelType_name[_NoSQLModelType_index[i]:_NoSQLModelType_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NumSupportedGraphModels-0]
}

const _GraphType_name = "NumSupportedGraphModels"

var _GraphType_index = [...]uint8{0, 23}

func (i GraphType) String() string {
	if i < 0 || i >= GraphType(len(_GraphType_index)-1) {
		return "GraphType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GraphType_name[_GraphType_index[i]:_GraphType_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NumSupportedTimeSeries-0]
}

const _TimeSeriesType_name = "NumSupportedTimeSeries"

var _TimeSeriesType_index = [...]uint8{0, 22}

func (i TimeSeriesType) String() string {
	if i < 0 || i >= TimeSeriesType(len(_TimeSeriesType_index)-1) {
		return "TimeSeriesType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TimeSeriesType_name[_TimeSeriesType_index[i]:_TimeSeriesType_index[i+1]]
}
