// Code generated by "stringer -type=NodeType -trimprefix=NodeType"; DO NOT EDIT.

package data

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NodeTypeServer-0]
	_ = x[NodeTypeDatabase-1]
	_ = x[NodeTypeTable-2]
	_ = x[NodeTypeColumn-3]
	_ = x[NodeTypeSchema-4]
	_ = x[NodeTypeSchemaDatabase-5]
	_ = x[NodeTypeSchemaTable-6]
	_ = x[NodeTypeSchemaColumn-7]
	_ = x[NodeTypeProperties-8]
	_ = x[NodeTypePropery-9]
	_ = x[NodeTypeRequest-10]
	_ = x[NodeTypeIntent-11]
	_ = x[NodeTypeResponse-12]
	_ = x[NodeTypeCustom-13]
}

const _NodeType_name = "ServerDatabaseTableColumnSchemaSchemaDatabaseSchemaTableSchemaColumnPropertiesProperyRequestIntentResponseCustom"

var _NodeType_index = [...]uint8{0, 6, 14, 19, 25, 31, 45, 56, 68, 78, 85, 92, 98, 106, 112}

func (i NodeType) String() string {
	if i < 0 || i >= NodeType(len(_NodeType_index)-1) {
		return "NodeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NodeType_name[_NodeType_index[i]:_NodeType_index[i+1]]
}
