// Code generated by "stringer -type=DataSourceType,SQLDialectType,NoSQLType,GraphType,TimeSeriesType -trimprefix=Type"; DO NOT EDIT.

package datasource

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SourceTypeSQL-0]
	_ = x[SourceTypeNoSQL-1]
	_ = x[SourceTypeGraph-2]
	_ = x[SourceTypeTimeSeries-3]
	_ = x[SourceTypeUndefined - -1]
}

const _DataSourceType_name = "SourceTypeUndefinedSourceTypeSQLSourceTypeNoSQLSourceTypeGraphSourceTypeTimeSeries"

var _DataSourceType_index = [...]uint8{0, 19, 32, 47, 62, 82}

func (i DataSourceType) String() string {
	i -= -1
	if i < 0 || i >= DataSourceType(len(_DataSourceType_index)-1) {
		return "DataSourceType(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _DataSourceType_name[_DataSourceType_index[i]:_DataSourceType_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PostgreSQL-0]
	_ = x[MySQL-1]
	_ = x[SQLite3-2]
	_ = x[NumSupportedSQLDialects-3]
}

const _SQLDialectType_name = "PostgreSQLMySQLSQLite3NumSupportedSQLDialects"

var _SQLDialectType_index = [...]uint8{0, 10, 15, 22, 45}

func (i SQLDialectType) String() string {
	if i < 0 || i >= SQLDialectType(len(_SQLDialectType_index)-1) {
		return "SQLDialectType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SQLDialectType_name[_SQLDialectType_index[i]:_SQLDialectType_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MongoDB-0]
	_ = x[Firestore-1]
	_ = x[Redis-2]
	_ = x[NumSupportedNoSQLModels-3]
}

const _NoSQLType_name = "MongoDBFirestoreRedisNumSupportedNoSQLModels"

var _NoSQLType_index = [...]uint8{0, 7, 16, 21, 44}

func (i NoSQLType) String() string {
	if i < 0 || i >= NoSQLType(len(_NoSQLType_index)-1) {
		return "NoSQLType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NoSQLType_name[_NoSQLType_index[i]:_NoSQLType_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NumSupportedGraphModels-0]
}

const _GraphType_name = "NumSupportedGraphModels"

var _GraphType_index = [...]uint8{0, 23}

func (i GraphType) String() string {
	if i < 0 || i >= GraphType(len(_GraphType_index)-1) {
		return "GraphType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GraphType_name[_GraphType_index[i]:_GraphType_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NumSupportedTimeSeries-0]
}

const _TimeSeriesType_name = "NumSupportedTimeSeries"

var _TimeSeriesType_index = [...]uint8{0, 22}

func (i TimeSeriesType) String() string {
	if i < 0 || i >= TimeSeriesType(len(_TimeSeriesType_index)-1) {
		return "TimeSeriesType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TimeSeriesType_name[_TimeSeriesType_index[i]:_TimeSeriesType_index[i+1]]
}
